export { default as Loading} from "./Loading"

export { default as SubmitBtn } from "./SubmitBtn"
export { default as Navbar} from "./Navbar"
export { default as Logo} from "./Logo"
export { default as FloatingLabel} from "./FloatingLabel"
export { default as MobileMenu} from "./MobileMenu"
export { default as PostFeeds} from "./PostFeeds"
export { default as Details} from "./Details"
export { default as Suggestions} from "./Suggestions"
export { default as ProfilePic} from "./ProfilePic"
